### ISSUE TITLE
Definition List not rendering in Nuxt 2

### ISSUE THREAD

**Issue by lilyx13** [wataru-chocola/remark-definition-list#30]
Hello, I'm working on a nuxt 2 project using the nuxt/content module. Definition lists are being rendered as paragraph tags, and the markdown to html compiler seems to completely ignore the white spaces between the colon and the text.

I wasn't sure if it was an issue with my repo, so I tried using it in a forked codesandbox that is using another remark plugin, and the definition-list one still does not render. I'm not sure if it's a syntax, configuration, or plugin issue.

[Here is the codesandbox](https://codesandbox.io/s/nostalgic-gates-iuz92) that I was experimenting in.

I've set up the nuxt.config.js content settings like this:
```
content: {
  markdown: {
    remarkPlugins: ['remark-definition-list']
  }
}
```
Versions that I'm using are:
nuxt: 2.15.7
@nuxt/content: 1.15.1
remark-definition-list: 1.1.0

**Comment by wataru-chocola** [comment]
@lilyx13 

I don't know nuxt at all, but at first glance, I think you need to specify `remark-rehype` handler for deflist somehow.
Do you know if `@nuxt/content` has API for this or there's other way to do it?

**Comment by wataru-chocola** [comment]
I took a look at code in `nuxt/content` which processes markdown ([content/parsers/markdown/index.js](https://github.com/nuxt/content/blob/ea976cee393a8fef14f5cd7572dfe0dd56473640/packages/content/parsers/markdown/index.js#L93)).

```javascript
      stream = this.processPluginsFor('remark', stream)
      stream = stream.use(remark2rehype, {
        handlers: handlers(highlighter),
        allowDangerousHtml: true
      })
      stream = this.processPluginsFor('rehype', stream)
```

and [`handlers` function](https://github.com/nuxt/content/blob/ea976cee393a8fef14f5cd7572dfe0dd56473640/packages/content/parsers/markdown/handlers/index.js):

```javascript
module.exports = highlighter => ({
  code: require('./code')(highlighter),
  paragraph: require('./paragraph'),
  html: require('./html')
})
```

There seems to be no way to set additional handlers.

**Comment by wataru-chocola** [comment]
I'll close this issue, but please let me know if there is anything I can do for you.
