### ISSUE TITLE
Enclosure of term-value groups in divs

### ISSUE THREAD

**Issue by etdr** [wataru-chocola/remark-definition-list#33]
I'm wondering if there could be some way, either in the markdown syntax or as a parameter given to the plugin, to wrap `<dt>`/`<dd>` groups with `<div>` tags? This seems to be legal HTML as per:

- [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_div_elements)
- [WHATWG `dl` spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element)

**Comment by wataru-chocola** [comment]
I'm afraid not.
